name: todoapp
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./ToDoApp.Web/Dockerfile
    ports:
      - 5000:80
    depends_on:
      api:
        condition: service_started

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./ToDoApp.API/Dockerfile
    ports:
      - 5001:5001
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=ToDoAppDocker;User Id=sa;Password=YourSTRONG!Passw0rd;TrustServerCertificate=True;
      - Cors__AllowedOrigins__0=http://localhost:5000
    depends_on:
      - sql-server

  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - 5002:1433
    environment:
      - SA_PASSWORD=YourSTRONG!Passw0rd
      - ACCEPT_EULA=Y

volumes:
  db-data:
